Upgraded version with several changes

diff --git a/purge-old-kernels b/purge-old-kernels
--- a/purge-old-kernels
+++ b/purge-old-kernels
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 #    purge-old-kernels - remove old kernel packages
 #    Copyright (C) 2012      Dustin Kirkland <kirkland@ubuntu.com>
@@ -20,56 +20,126 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+export VERSION=1.1
+
+SCRIPT="$(basename $0)"
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
+
+
 # Ensure we're running as root
 if [ "$(id -u)" != 0 ]; then
-	echo "ERROR: This script must run as root.  Hint..." 1>&2
+	echo -e "${RED}ERROR: This script must run as root.  Hint...${NC}" 1>&2
 	echo "  sudo $0 $@" 1>&2
 	exit 1
 fi
+
+print_version() {
+   echo "$SCRIPT $VERSION"
+}
+
+print_help () {
+   echo "$SCRIPT $VERSION"
+   echo "Purge old kernels tool"
+   echo ""
+   echo "Usage: $SCRIPT [OPTIONS]"
+   echo "Recognized options:"
+   echo "  -h,  --help                       display this help and exit"
+   echo "  -v   --version                    display $SCRIPT version and exit"
+   echo "  -s,  --show-installed-kernels     display installed kernels"
+   echo "  -k,  --keep N                     keep last N kernels"
+   echo "                                    ALWAYS keep the currently running kernel"
+   echo "  -q,  --quiet                      remove old kernels without asking"
+   echo "  -n,  --no-rm-modules              don't remove non installed kernels directories in /lib/modules"
+   echo
+   echo "Any unrecognized option will be passed straight through to apt-get"
+   echo 
+}
+
+parse_options() {
+   TEMP=`getopt -o hvsk:qn --long help,version,show-installed-kernels,keep:,quiet,no-rm-modules -n 'purge-old-kernels' -- "$@"`
+
+   if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+   eval set -- "$TEMP"
+
+   while true; do
+     case "$1" in
+       -h | --help)
+                 print_help
+                 exit 0
+                 ;;
+       -v | --version)
+                 print_version
+                 exit 0
+                 ;;
+       -s | --show-installed-kernels )
+                 show_installed_kernels
+                 shift
+                 ;;
+       -n | --no-rm-modules )
+                 NO_RM_MODULES=true
+                 shift
+                 ;;
+       -k | --keep )
+                 KEEP="$2"
+                 shift 2
+                 ;;
+       -q | --quiet )
+                 APT_OPTS="$APT_OPTS -qy"
+                 shift 1
+                 ;;
+       -- )
+                 shift
+                 break
+                 ;;
+       * )
+                 echo "Internal error: doesn't recognize argument '$1'"
+                 exit 1
+                 ;;
+     esac
+   done
+}
+
+show_installed_kernels () {
+   INSTALLED_KERNELS=$(ls /boot/vmlinuz-* | sed -e "s/^\/boot\/vmlinuz-//" | awk -F'[.-]' '{print $1"\t"$2"\t"$3"\t"$4"\t"$0}' | sort -k1 -k2 -k3 -k4 -n | cut -f5)
+   echo -e "Installed kernels:"
+   echo -e "${GREEN}$INSTALLED_KERNELS${NC}"
+}
 
 # NOTE: This script will ALWAYS keep the currently running kernel
 # NOTE: Default is to keep 2 more, user overrides with --keep N
 KEEP=2
 # NOTE: Any unrecognized option will be passed straight through to apt-get
 APT_OPTS=
-while [ ! -z "$1" ]; do
-	case "$1" in
-		--keep)
-			# User specified the number of kernels to keep
-			KEEP="$2"
-			shift 2
-		;;
-		*)
-			APT_OPTS="$APT_OPTS $1"
-			shift 1
-		;;
-	esac
-done
+VERBOSE=false
+NO_RM_MODULES=false
+
+parse_options "$@"
+
+echo "We keep last $KEEP installed kernels"
 
 # Get kernel type: pve or not
 PVE_KERNEL=$(uname -r|grep pve)
 
 # Build our list of kernel packages to purge
-if [ -n "$PVE_KERNEL" ]; then
-   CANDIDATES=$(ls /boot/vmlinuz-* | sed -e "s/^\/boot\/vmlinuz-//" | awk -F'[.-]' '{print $1"\t"$2"\t"$3"\t"$4"\t"$0}' | sort -k1 -k2 -k3 -k4 -n | cut -f5 | head -n -${KEEP} | grep -v "$(uname -r)$" | grep -oiE '[0-9]+\.[0-9]+\.[0-9]+-[0-9]+')
+CANDIDATES=$(ls /boot/vmlinuz-* | sed -e "s/^\/boot\/vmlinuz-//" | awk -F'[.-]' '{print $1"\t"$2"\t"$3"\t"$4"\t"$0}' | sort -k1 -k2 -k3 -k4 -n | cut -f5 | head -n -${KEEP} | grep -v "$(uname -r)$" | grep -oiE '[0-9]+\.[0-9]+\.[0-9]+-[0-9]+')
 
+if [ -z "$PVE_KERNEL" ]; then
    for c in $CANDIDATES; do
-       PURGE="$PURGE $(dpkg -l | grep -e pve-.*$c | awk '{print $2}' |  tr "\n" " ")"
+      PURGE="$PURGE $(dpkg -l | awk '{print $2}' | grep -e ^linux.*$c |  tr "\n" " ")"
    done
 else
-   # Remove old /lib/modules kernel directories
-   find /lib/modules -mindepth 1 -maxdepth 1 $(dpkg --get-selections | grep 'linux-modules' | grep -v -e 'extra' | awk '{print $1}' | sed 's/linux-modules-/-not -name /' | tr "\n" " ") -exec rm -fr {} \;
-
-   CANDIDATES=$(ls /boot/vmlinuz-* | sed -e "s/^\/boot\/vmlinuz-//" | awk -F'[.-]' '{print $1"\t"$2"\t"$3"\t"$4"\t"$0}' | sort -k1 -k2 -k3 -k4 -n | cut -f5 | head -n -${KEEP} | grep -v "$(uname -r)$" | grep -oiE '[0-9]+\.[0-9]+\.[0-9]+-[0-9]+')
-
    for c in $CANDIDATES; do
-       PURGE="$PURGE $(dpkg -l|grep -e linux-.*$c | awk '{print $2}' |  tr "\n" " ")"
+      PURGE="$PURGE $(dpkg -l | awk '{print $2}'| grep -e ^pve-.*$c |  tr "\n" " ")"
    done
 fi
 
 if [ -z "$PURGE" ]; then
-	echo "No kernels are eligible for removal"
-	exit 0
+   echo "No kernels are eligible for removal"
+   exit 0
 fi
 
 # Purge old installed kernels
@@ -85,7 +155,7 @@ fi
 # Purge old uninstalled kernels
 [ -n "$REMOVED" ] && apt-get $APT_OPTS remove --purge $REMOVED
 
-if [ -z "$PVE_KERNEL" ]; then
+if [ -z "$PVE_KERNEL" ] && [ "$NO_RM_MODULES" = false ]; then
    # Remove old /lib/modules kernel directories
    find /lib/modules -mindepth 1 -maxdepth 1 $(dpkg --get-selections | grep 'linux-modules' | grep -v -e 'extra' | awk '{print $1}' | sed 's/linux-modules-/-not -name /' | tr "\n" " ") -exec rm -fr {} \;
 fi
